name: Linter & formatter

on:
  workflow_dispatch:
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run linter
        uses: chartboost/ruff-action@v1
        with:
          args: check
      - name: Run formatter
        uses: chartboost/ruff-action@v1
        with:
          args: format --check
